### ISSUE TITLE
Capability support for heat.

### ISSUE THREAD

**Issue by ExpensiveKoala** [MikeLydeamore/ExNihiloAdscensio#1]
On top of checking if a block is registered, crucibles could also check if a tile-entity has a capability for the heat. 

This allows for addon mods to make machines generate an arbitrary amount of heat that isn't a constant depending on what block it is.

For example, one could make the ic2 heat system work with crucibles.

**Comment by MikeLydeamore** [comment]
I like this. I'll look into it.

**Comment by SnakeFang** [comment]
I made a Capability system, but it's up to mod authors to use it for now.
Too lazy to implement any default compatibility right now.
