### ISSUE TITLE
Crash at startup with new version 0.1.13 (1.10.2). (One Probe dependency maybe?)

### ISSUE THREAD

**Issue by ate0ate** [MikeLydeamore/ExNihiloAdscensio#100]
I just updated to 0.1.13 and now I get this crash at startup...

http://pastebin.com/yPjvYYgj

The prior version works just fine.
This is using forge 12.18.3.2221
Thanks!

**Comment by MikeLydeamore** [comment]
Should be fixed in 298691d479ef350c47a52d5a406bbddc8b3a877f
