### ISSUE TITLE
Urgent: do *not* ship TOP API with your own mods

### ISSUE THREAD

**Issue by McJty** [MikeLydeamore/ExNihiloAdscensio#101]
FYI: https://github.com/McJty/TheOneProbe/issues/141

Please do not ship the TOP API with your own mod. I just updated the API and now things crash because you version is outdated. It is strongly recommended to never bundle API's with mods. That causes conflicts and it is not needed

**Comment by McJty** [comment]
The recommended way is to just get the api using maven (put lines for that in your build.gradle). That way you can use it in your project but it will not get included with it

**Comment by MikeLydeamore** [comment]
This used to be handled by the @API annotation. Is that no longer the case?

**Comment by MikeLydeamore** [comment]
Also, is the other half of this solution to implement @Optional.Annotation to strip the annotation when TOP is not included?

**Comment by McJty** [comment]
Well the problem seems to be that the top apI is actually bundled with your jar
I usually just let grade handle this

**Comment by MikeLydeamore** [comment]
OK, so what is the solution to crashes from any TOP annotations that are present when TOP is not also loaded?

**Comment by McJty** [comment]
Check out this tutorial where you can do it without even needing @Optional. That's the technique I use in all my other mods:

http://modwiki.temporal-reality.com/mw/index.php/API_TOP-1.9

You can also use @Optional
