### ISSUE TITLE
Crash on custom FluidBlockTransformerRegistry.json

### ISSUE THREAD

**Issue by Thyriel** [MikeLydeamore/ExNihiloAdscensio#106]
Not sure if this is supposed to be customizeable, but just in case...
I tried adding a recipe for applied energistics2 that transforms water+certus quartz seed in a barrel to a certus quartz by adding the following to the json:

> {
>     "fluidName": "water",
>     "input": {
>       "name": "appliedenergistics2:crystal_seed",
>       "meta": 0
>     },
>     "output": {
>       "name": "appliedenergistics2:material",
>       "meta": 0
>     }
>   },

As soon as i add the certus quartz seed then to a barrel with water the client crashes (and keeps crashing until i removed the barrel via console commands on the server): http://pastebin.com/9BX2SGWk

My guess is that it doesn't know what to display inside the barrel as there is no configuration for that.

Version: exnihiloadscensio-1.10.2-0.1.16.jar

**Comment by MikeLydeamore** [comment]
I kinda hoped this would just display a broken texture, not crash out, but nonetheless,

the output for FluidBlockTransformerRegistry is supposed to be a block not an item. I suspect this is causing this.

**Comment by Thyriel** [comment]
I feared it would be something like that ;)
May i place it then as an enhancement wish to make it possible getting items out if it (maybe add an optional option to specify a block for a texture to display).

Thought it would be a great enhancement (=faster way) to the AE2 way of turning crystal seeds into crystals (thrown in still water and then waiting 2 or 3 ages until the crystals have "grown").

**Comment by MikeLydeamore** [comment]
I think I may have "fixed" the crash on another issue. Instead you'll get a broken texture image (for now). Can you let me know if this is the case?

**Comment by MikeLydeamore** [comment]
Gonna assume this worked fine. Reopen if the issue persists.
