### ISSUE TITLE
Crucibles only support block inputs

### ISSUE THREAD

**Issue by KnightMiner** [MikeLydeamore/ExNihiloAdscensio#113]
I am trying to add a feature for crucibles melting the ore chunks into molten metals from Tinkers Construct (as an early game smeltery), but I ran into the issue that the chunks are now items instead of blocks as they were in 1.7, so the crucible cannot melt them simply because it cannot render non-blocks ([this line is the first one it crashes on](https://github.com/MikeLydeamore/ExNihiloAdscensio/blob/master/src/main/java/exnihiloadscensio/tiles/TileCrucible.java#L203), I can provide a report but it obviously is just unable to get a block from that item in the report).

Any chance a feature can be added for a recipe to have a delegate display blockstate so items recipes can be added? Simply, if a delegate exists, that is used for display. If no delegate exists and an item is inputted, just display the missing texture.

**Comment by MikeLydeamore** [comment]
Just a note: In my testing, Tinkers Fluids rendered without their colour, but I _think_ this isn't on my end, as EnderIO fluids rendered just fine.

**Comment by MikeLydeamore** [comment]
Also the JSON looks something like this:
`"exnihiloadscensio:itemOreIron:1": {
    "fluid": "iron",
    "amount": 250,
    "textureOverride": {
       "name": "minecraft:iron_ore",
       "meta": 0
    }
  }`

**Comment by KnightMiner** [comment]
Thanks!

----

I'm pretty sure Ender IO does not use tinting for their fluids, they are just a texture per fluid, so there is a chance you are simply missing support for fluid tinting. Tinkers Construct uses the same texture for all fluids since it has a lot and just tints it similarly to vanilla grass.

Adding support is a bit of work since you have to turn a single integer color into four individual numbers, but I have some example code on how to do that [here](https://github.com/KnightMiner/Ceramics/blob/master/src/main/java/knightminer/ceramics/client/BarrelRenderer.java#L68-L82) if you want it (note the additional .color() function for the quads)

I'll open a second issue for this if desired.

**Comment by KnightMiner** [comment]
Slight bug with this in my testing: it seems that items always show a missing texture until they start melting. As a result, there will be a missing texture for about a tick in a "heated" crucible, and always a missing texture in a non-heated crucible.
