### ISSUE TITLE
Stone Barrels: Lava/Water to Obsidian only tolarates 1 EnderIO Path

### ISSUE THREAD

**Issue by ArkavianX** [MikeLydeamore/ExNihiloAdscensio#116]
I remember this working at one point an as far as I can read in the configuration everything is enabled to ensure compatibility with EnderIO. 

So what I am trying to do is use EnderIO fluid conduits to pump in lava from side and water from EnderIO resevior from top. 

The barrels will ONLY accept fluids from ONE source, they completely ignore the second. 

I've tried the Water/Lava to cobblestone recipe as well, still failed.

Had no issue with 1 fluid source and a solid item: Water/Dust to Clay, Lava/Redstone to Netherrack etc. 

Currently using Skyfactory 3 from Curse, had same issue in Ozone 2, been a while since I've actually used this method (magical crops spoiled me)

**Comment by MikeLydeamore** [comment]
To make obsidian, the water source block must be placed in world above the barrel filled with lava. Not piped into the barrel.

To make cobblestone, swap the lava and water.

**Comment by ArkavianX** [comment]
Was this always the case? I seem to remember otherwise a couple years ago. Will try....

**Comment by MikeLydeamore** [comment]
It's been the case for as long as I can remember.
