### ISSUE TITLE
Wooden barrel becomes "unusable", it thinks it still has dirt

### ISSUE THREAD

**Issue by TheQuadShot** [MikeLydeamore/ExNihiloAdscensio#122]
I'm on a standalone/single player, Sky Factory 3(v.3.0,8), exnihiloadscensio-1.10.2-0.1.17. If I shut down my server and there is dirt in the wooden barrel, when I start the server back up right clicking gives me a block of dirt, but the block doesn't update. It still looks like it has dirt in it and the tool tip say's it has dirt in it, but there is no dirt. If I break the block and place it again it's fine.

**Comment by MikeLydeamore** [comment]
Should be fixed in 5c4ce92384b72761d3d6494310048d5498c8c69e
