### ISSUE TITLE
[Question] Adding Sieve Drops with Minetweaker

### ISSUE THREAD

**Issue by MokahTGS** [MikeLydeamore/ExNihiloAdscensio#123]
I'm trying to add Mystical Agriculture's Prosperity Shards to a gravel drop in the sieve and I can't seem to get it to work.

Do I have to define the mesh type too?  If so, how?

Here is my script:  http://pastebin.com/aFq1TTwe

**Comment by Flabort** [comment]
You don't have to use minetweaker. This mod natively allows you to change mesh drops via JSON in the configs. Go to your ex nihilo config directory for the mod(pack), such as C:\Users\Owner\Documents\Curse\Minecraft\Instances\MyModpack\config\exnihiloadscensio , and open up SieveRegistry.JSON in wordpad or a program of your choice.

**Comment by MikeLydeamore** [comment]
I'm not sure on the specifics on Minetweaker support (it has nothing to do with me), but all sieve drops need a mesh type as mentioned.

I suggest checking in with the Minetweaker folks for the specifics.
