### ISSUE TITLE
[Crash 1.10.2] Adding Liquid Transforms

### ISSUE THREAD

**Issue by MokahTGS** [MikeLydeamore/ExNihiloAdscensio#125]
I'm trying to add a liquid transform for water into Ars Magica 2's Liquid Essence and can't seem to get it to work.

Here's what I have:

[
  {
    "inputFluid": "water",
    "outputFluid": "witchwater",
    "transformingBlocks": [
      {
        "name": "minecraft:mycelium",
        "meta": 0
      }
    ],
    "blocksToSpawn": [
      {
        "name": "minecraft:brown_mushroom",
        "meta": 0
      },
      {
        "name": "minecraft:red_mushroom",
        "meta": 0
      }
    ],
    "duration": 12000
  },
  {
    "inputFluid": "water",
    "outputFluid": "arsmagica2:liquid_essence",
    "transformingBlocks": [
      {
        "name": "arsmagica2:block",
        "meta": 2
      }
    ],
    "duration": 12000
  }
]

Is this fluid just not supported somehow?

**Comment by MokahTGS** [comment]
Well got it to work but it crashed at 50% transform;

http://pastebin.com/iAuchn8W

**Comment by KnightMiner** [comment]
Are you sure that is the right ID for the fluid? It looks like a block ID, fluid IDs have no resource locations.

**Comment by MokahTGS** [comment]
https://www.dropbox.com/s/a56pi9jrobehm84/2017-03-25_15.11.21.png?dl=0

What am I looking for?

**Comment by MokahTGS** [comment]
Ok, removing the resource location seems to have stopped the crash.  Thanks
