### ISSUE TITLE
error text viewing blocks with theoneprobe

### ISSUE THREAD

**Issue by BrianEdmonds** [MikeLydeamore/ExNihiloAdscensio#126]
When I look at Ex Nihilo Adscensio blocks using theoneprobe (worn as a bauble), I see an error message as an extra (Error: exnihiloadscensio:topprovider). Screenshot:

![2017-03-28_20 13 25](https://cloud.githubusercontent.com/assets/18468613/24436954/38eb1630-13f3-11e7-961e-a8e7e7f6069e.png)

This applies to at least the sieve, as shown, and the stone barrel. Relevant versions include:
  Minecraft 1.10.2
  Forge 12.8.3.2254
  Ex Nihilo Adscensio 0.1.17
  theoneprobe 1.4.4
  Baubles 1.3.9

**Comment by MikeLydeamore** [comment]
Already reported in #111. Awaiting fix on TOP for me to fix.

**Comment by BrianEdmonds** [comment]
Thanks, sorry for the dup. I did look through the open issues, but didn't trigger that an issue with console spam (that I wasn't seeing) would be related.
