### ISSUE TITLE
[1.10.2] Diamonds From Trees

### ISSUE THREAD

**Issue by MokahTGS** [MikeLydeamore/ExNihiloAdscensio#128]
Smashing an oak tree to get woodchips also is giving a bunch of diamonds.  Is this somewhere in the jsons that I can turn off?

**Comment by BrianEdmonds** [comment]
Yeah, that was beautiful while it lasted, but it's already been fixed. Per an earlier closed issue, it was a test recipe in the code that snuck into release.

**Comment by MokahTGS** [comment]
Ok, so is the updated version live?  I'm looking at the 1.10.2 version, BTW

**Comment by BrianEdmonds** [comment]
The previous issue was #114. (Found by an easy search on the issue tracker, btw.) The fix was pushed 23 days ago, so I'd guess is in the current release, but I don't have a working world with that currently, so can't say for certain.

**Comment by MokahTGS** [comment]
Well, I'll double check but I'm pretty sure we are running the latest version, which would mean that the "fix" should have been included and this issue shouldn't have happened.

**Comment by MikeLydeamore** [comment]
The change has been pushed and is on the latest version of the mod.

**However**, it cannot change existing JSON files. If you look in the HammerRegistry.json file there should be a line that is something like this:
`"minecraft:log:0": [
    {
      "stack": {
        "name": "minecraft:diamond",
        "amount": 1,
        "meta": 0
      },
      "miningLevel": 0,
      "chance": 1.0,
      "fortuneChance": 0.0
    }
]`

Simply delete that entry and the problem should be solved.

**Comment by MikeLydeamore** [comment]
Please reopen if issue persists.
