### ISSUE TITLE
How to obtain crushed/broken versions of modded ores

### ISSUE THREAD

**Issue by tyler489** [MikeLydeamore/ExNihiloAdscensio#129]
Currently building a modpack and i knowticed that osmium and a few other mod ores dont have a crushed/broken version and are not added to sieve loottable. Can you tell me how to make them register and i can add them to sieveregistry.json myself. Thanks :)

**Comment by BrianEdmonds** [comment]
I just did this for the Mekanism based modpack I'm working on. I added 
the following to OreRegistry.json:

   {
     "name": "copper",
     "color": {
       "r": 1.0,
       "g": 0.6,
       "b": 0.2,
       "a": 1.0
     }
   },
   {
     "name": "tin",
     "color": {
       "r": 0.9,
       "g": 0.9,
       "b": 0.9,
       "a": 1.0
     }
   },
   {
     "name": "osmium",
     "color": {
       "r": 0.75,
       "g": 0.75,
       "b": 0.9,
       "a": 1.0
     }
   },

And the following to the gravel section in SieveRegistry.json:

     {
       "drop": {
         "name": "exnihiloadscensio:itemOreCopper",
         "meta": 0
       },
       "chance": 0.2,
       "meshLevel": 2
     },
     {
       "drop": {
         "name": "exnihiloadscensio:itemOreCopper",
         "meta": 0
       },
       "chance": 0.2,
       "meshLevel": 3
     },
     {
       "drop": {
         "name": "exnihiloadscensio:itemOreTin",
         "meta": 0
       },
       "chance": 0.2,
       "meshLevel": 2
     },
     {
       "drop": {
         "name": "exnihiloadscensio:itemOreTin",
         "meta": 0
       },
       "chance": 0.2,
       "meshLevel": 3
     },
     {
       "drop": {
         "name": "exnihiloadscensio:itemOreOsmium",
         "meta": 0
       },
       "chance": 0.2,
       "meshLevel": 2
     },
     {
       "drop": {
         "name": "exnihiloadscensio:itemOreOsmium",
         "meta": 0
       },
       "chance": 0.2,
       "meshLevel": 3
     },
     {
       "drop": {
         "name": "exnihiloadscensio:itemOreOsmium",
         "meta": 0
       },
       "chance": 0.1,
       "meshLevel": 4
     },

I may tune them later, and I could have missed a detail. It's 
definitely working for sieving so far. I've not tried smelting them yet.

**Comment by tyler489** [comment]
definitly works @BrianEdmonds however how do you chose colors... is it trail and error? as currently my broken yellorite has bright pink streaks... amusing but not quite what i want https://gyazo.com/b2ec303cda2cffcd57cbc6bb43bcc1e3

**Comment by MikeLydeamore** [comment]
Colours are rgb divided by 255. There's websites that let you pick off a
colour wheel and spit out the RGB.

**Comment by tyler489** [comment]
yep figured that out already ;)
