### ISSUE TITLE
Crash on load

### ISSUE THREAD

**Issue by leezboy** [MikeLydeamore/ExNihiloAdscensio#134]
Hi, I added Ex Nihilo Adscensio to my modpack but when I load it up it crashes. I checked the crash log but I don't understand any of it. Any help would be appreciated, also if anyone can see anything else wrong with the pack then please let me know so I can fix it.

Here is the full crash report: [https://pastebin.com/vL5WsSdz](url)

Thanks

**Comment by BrianEdmonds** [comment]
This has been reported a number of times, and I believe it's supposed to
be fixed in 0.1.20.

**Comment by leezboy** [comment]
Ok thanks I'll try that version.

**Comment by MikeLydeamore** [comment]
I'm gonna guess by the silence that this is fixed. Please reopen if the issue persists.

**Comment by leezboy** [comment]
Sorry I completely forgot to post back, yes updating the mod fixed the issue. Thanks BrianEdmonds
