### ISSUE TITLE
JEI Support

### ISSUE THREAD

**Issue by Darkosto** [MikeLydeamore/ExNihiloAdscensio#14]
Please add support for JEI :D

**Comment by MikeLydeamore** [comment]
Sieve support added in bebae6ef92716b638d7413bf2a5e0868799700c9

**Comment by SnakeFang** [comment]
Added at some other point that I'm too lazy to go find:
- Hammer
- Fluid -> Fluid
- Fluid -> Block (Right-Click)
- Fluid -> Block (Fluid on top)

**Comment by MikeLydeamore** [comment]
I think everything is added now.
