### ISSUE TITLE
Any possibility of an update to 1.11 or 1.12? 

### ISSUE THREAD

**Issue by Tylerun** [MikeLydeamore/ExNihiloAdscensio#147]
Hey just wondering if theirs any possibility of an update?

**Comment by darthvader45** [comment]
I noticed a 1.11.2 branch.  May yet see if it is ready and perhaps compile it to test, but not sure.

**Comment by BloodWorkXGaming** [comment]
I am currently working on a 1.12 version.

**Comment by darthvader45** [comment]
Alrighty, I have actually managed to compile a 1.11.2 version as well, if you'd like me to maintain it while you focus on 1.12, thank you.  If not, it's fine.  No errors on it for now, I'll have to test and push it in every way I can.

**Comment by BloodWorkXGaming** [comment]
Yes, I have no problem taking on 1.12.
We have no way of releasing it on curse, I will probably make a separate project and maybe add a few blocks of my own.

**Comment by darthvader45** [comment]
Can I be involved as a maintainer for the 1.11.2 version?  All credit will go to you for updates and Erasmus_Crowley for the idea and original mod. I can also send a copy to insaneau, as he is the one currently maintaining the project on Curse/CurseForge.

**Comment by BloodWorkXGaming** [comment]
We can work something like that out, will tell your more later when I have
time, any way to contact you directly? Discord maybe?

darthvader45 <notifications@github.com> schrieb am Mo., 7. Aug. 2017, 17:19:

**Comment by Tylerun** [comment]
Hmmm this sounds like a fun time. Why cant it be thrown up on curse?

**Comment by darthvader45** [comment]
Discord sounds nice.  Last_Dovahkiin's my username, what's yours?  I'll add ya.

**Comment by BloodWorkXGaming** [comment]
Mine is BloodWorkXGaming#2564, the problem with curse is that we are not
the owner/maintainer of the original ex nihilo, therefore we can't change
anything, and he didn't do anything the last few month therefore i don't
know whether he is still in the minecraft community. Luckily this project
is MIT therefore we have the right to fork and update it.

darthvader45 <notifications@github.com> schrieb am Mo., 7. Aug. 2017 um
17:50 Uhr:

**Comment by Tylerun** [comment]
Well if we have the files we are allowed to upload to curse but someone has to manually add it to the overrides so that it goes through so it still can be added to packs manually if im not mistaken. Shouldn't be to hard to throw up another project either and add him to the rights. Could give him owner of the new project lol
