### ISSUE TITLE
Can't Pull From Barrels/Crucibles with 2+ stacked buckets in hand

### ISSUE THREAD

**Issue by Darkosto** [MikeLydeamore/ExNihiloAdscensio#17]
When you hold 2 or more buckets stacked, you cannot pull liquids from the barrels or crucibles like you are able to with Vanilla sources.

**Comment by MikeLydeamore** [comment]
Fixed in 73c150b669c5aec450aedf3608e35e6d8c485a44 and 93e6931a62a883e1d4e334e5a19bfbc7d9011dff
