### ISSUE TITLE
Please add WAILA Support

### ISSUE THREAD

**Issue by Darkosto** [MikeLydeamore/ExNihiloAdscensio#18]
Please! I don't know what is happening most of the time. Please add WAILA support so I look less dumb on stream ples.

**Comment by MikeLydeamore** [comment]
Added in f331ad04d4e586c014755f1124ac371de7c3d11a and dd1fff4dcc009976b2d93226334639faea12cbef and 80794fc084730f3d37492a951f5a520dab793bb3

Still have crucible to go.

**Comment by SnakeFang** [comment]
Crucible is done (I think)

**Comment by MikeLydeamore** [comment]
I think everything is done? Lemme know if it's not.
