### ISSUE TITLE
Dust does not fall like sand

### ISSUE THREAD

**Issue by ExpensiveKoala** [MikeLydeamore/ExNihiloAdscensio#19]
You can make it fall by extending BlockFalling. Extending BlockSand gives it the blockstates of sand (red sand, regular sand, etc...).

So I recommend you make your BlockBase into an interface instead so that even if a block doesn't extend BlockBase you can make it so that you don't have to rewrite the code for registering each time.

**Comment by MikeLydeamore** [comment]
TIL that dust used to fall

Added in 77cefb7178b53b39c060ae5d5b20c0bc343f8e68
