### ISSUE TITLE
Make sure second registry is loaded from config in Fluid Transformer

### ISSUE THREAD

**Issue by SnakeFang** [MikeLydeamore/ExNihiloAdscensio#29]
There is an "internal" Map of String -> FluidTransformer, input fluid -> transformation data, in registries.FluidTransformRegistry that isn't initialized from the loadJson method. One fix is simply iterating through gsonInput (aka registry), and registering each one into registryInternal.
Example:
...
registry = gsonInput;
for(FluidTransformer transformer : gsonInput)
    registryInternal.put(transformer.getInputFluid(), transformer);
...

Obviously there are other ways of doing this, this is the way that came to my mind.
Good luck modding!

**Comment by MikeLydeamore** [comment]
Thanks :-)
