### ISSUE TITLE
You didn't fix all the scala imports. Screw scala.

### ISSUE THREAD

**Issue by SnakeFang** [MikeLydeamore/ExNihiloAdscensio#30]
There's still a scala Arrays import in barrel.modes.transform.BarrelModeFluidTransform
FYI this and my last two issues are on the 1.9 branch, I didn't even look at master since it's kinda outdated.

**Comment by SnakeFang** [comment]
Pro tip if you use eclipse: Preferences -> Java -> Appearance -> Type Filters, and add scala.* as a filter. No more auto Scala imports. Yay!

**Comment by MikeLydeamore** [comment]
...And added scala to the blacklist.
