### ISSUE TITLE
Hammer Crash

### ISSUE THREAD

**Issue by Darkosto** [MikeLydeamore/ExNihiloAdscensio#41]
Crash when using the compressed hammer from Ex Compressum on Sugar Cane, but this issue is actually an Ex Nihilo issue: http://pastebin.com/AbL6Rej8

ItemInfo.item is nullable as Item.getItemFromBlock can return null (in the case of sugar canes, for example), so it needs to null-check in the hashCode function, and .equals as well

**Comment by SnakeFang** [comment]
Fixed (But I can't close his issues)
