### ISSUE TITLE
Crashing version 0.1.0

### ISSUE THREAD

**Issue by mjctechguy** [MikeLydeamore/ExNihiloAdscensio#47]
Crashing when loading the game

MC Version: 1.10.2

Installed mods: Ex Nihilo Adscensio (0.1.0)

Forge Version: Both Recommend (1.10.2 - 12.18.2.2099) and Latest (1.10.2 - 12.18.2.2151) crash with mod installed

Log: https://gist.github.com/215bd03316b48568b101af1f4417434c

**Comment by gammagamer** [comment]
Same issue here, it seems that the mod tries to register itemOreGold twice.

**Comment by Lunchington** [comment]
having the issue as well with the gold ore registering twice

java.lang.IllegalArgumentException: The name exnihiloadscensio:itemOreGold has been registered twice, for exnihiloadscensio.items.ore.ItemOre@75c0e6be and exnihiloadscensio.items.ore.ItemOre@3dfe520.

**Comment by MikeLydeamore** [comment]
Fixed in 9cacfe697a8838199cf62b272b76ee6be6d77f66
