### ISSUE TITLE
Incompatibility with Silent's gems mod/Library mod

### ISSUE THREAD

**Issue by DatrixTHLK** [MikeLydeamore/ExNihiloAdscensio#48]
https://github.com/SilentChaos512/SilentGems/issues/83
Hi there,

The crash log contained within the referenced issue shows that Silent Gems being the culprit. When taking out Adscensio, Minecraft works just fine. If you aren't already aware, that is. Adscensio : 0.1.1 (beta) forge 2151

**Comment by SilentChaos512** [comment]
I noticed this mod replaces the vanilla Efficiency and Fortune enchantments in the enchantment registry. The crash report points to where I add the recipe for my Efficiency enchantment token ([this line](https://github.com/SilentChaos512/SilentGems/blob/master/common/net/silentchaos512/gems/item/ItemEnchantmentToken.java#L406)). That references the Enchantments class, which contains the original enchantment.

I would suggest registering separate versions of Efficiency and Fortune for the meshes. I haven't seen where mesh enchants are checked, but you should be able to check for both the mod and vanilla versions for compatibility with existing worlds.

**Comment by MikeLydeamore** [comment]
Hmm sorry about that... not sure how that slipped through.

Should be fixed in 61de1403ad9a9542806c5539d4fe8bcab2ecf580

**Comment by DatrixTHLK** [comment]
Thank you for the response and fix Mike. I appreciate it.
