### ISSUE TITLE
OreRegistry not working with modded ores

### ISSUE THREAD

**Issue by RealGrep** [MikeLydeamore/ExNihiloAdscensio#49]
Using version 0.1.2 and trying to add various modded ores to the OreRegistry. However, it is not working. I get various lines such as:

[Server thread/ERROR] [Ex Nihilo Adscensio]: Error parsing JSON: Invalid Item: {"name":"draconicevolution:draconium_ingot","meta":0}

Now, this does exist, but I think it doesn't exist yet when you're trying to process the OreRegistry.json file. Perhaps being run at the wrong stage? The crash log doesn't contain these lines since it seems to bomb on something else that seems unrelated. However, they are in the fml-server-latest.log file:

https://gist.github.com/RealGrep/8ca5ca7a25c5f464b16de0727ed3dc22

The OreRegistry.json file:

https://gist.github.com/RealGrep/03bfbd1c11624a7e0f2eb180983f3548

(As an aside, you might think of registering a barrel recipe for putting sand in a witchwater barrel to make soul sand as a default recipe.)

Thank you!
EDIT: I see from the code, it should be already trying to add some ores by default such as tin, etc. For the same reason, those are not showing up by default, either. The only ones that showed up with a default install are iron and gold. Basically, vanilla things only. I don't think preInit is the right place to load it.

**Comment by RealGrep** [comment]
Ok, looked at it some more. This is basically over my head, so I will leave it to you and spare you a crappy pull request. But I moved this line in ExNihiloAdscensio from preInit to init:

`OreRegistry.loadJson(new File(configDirectory, "OreRegistry.json"));`

Now it loads and actually works. However, all the textures are broken. So the model registrations also have to be moved to the init, but I'm told the registrations have to be done differently in init than in preInit.

Apparently, you would need to call "Minecraft.getMinecraft.renderItem.itemModelMesher.register" instead of "ModelLoader.setCustomModelResourceLocation" in places like blocks/BlockBase. Just passing that along in case it's helpful, but moving the renderer registrations to init is beyond my currently poor knowledge of MC modding.

Another problem that I *can* fix is your gradlew is too old for the build.gradle file, so it won't build as is. I'll submit a pull request to fix that shortly.

Thanks! Can't wait until this works, because it's looking very promising.

**Comment by MikeLydeamore** [comment]
Should be fixed in 10722e5d254458b157d4301ad94173cab7f7ba62
Thanks for the detailed reports :-)
