### ISSUE TITLE
Enchantments not registered correctly.

### ISSUE THREAD

**Issue by darkhax** [MikeLydeamore/ExNihiloAdscensio#51]
Forge made Enchantment extend `net.minecraftforge.fml.common.registry.IForgeRegistryEntry.Impl<Enchantment>`, meaning it is now possible to register them using `GameRegistry#register`. While the old way of registering enchantments works, it is better to let Forge handle the IDs rather than handling them yourself through config. Doing things the old way will also cause incompatibilities with Wawla, Enchanting Plus and Enchantment Descriptions, along with any other mod which expects the newer system to be used. 

It is very easy to switch to the new system, just call `setRegistryName` in the enchantment constructor, or use it as a builder method. And then call `GameRegistry#register`. Same way you do items and blocks. If you don't want to switch to the new system for legacy reasons, adding `setRegistryName` and keeping your current registry will fix the compatibility issues, or at least the ones with my mods. I would not recommend the mixed solution though, as mods will use that to lookup your enchantment rather than the numeric ID and they will get null results.

**Comment by MikeLydeamore** [comment]
That is way easier. Fixed in 2a6f8f86cc2f5b4f27a64dc4bfc6ca07bdb0181b
