### ISSUE TITLE
Issue when removing mesh when in the middle of sieving a block

### ISSUE THREAD

**Issue by Darkosto** [MikeLydeamore/ExNihiloAdscensio#52]
The sieve bugs out a bit when you remove a sieve mesh while a block is being sieved.

**Comment by MikeLydeamore** [comment]
Should (?) be fixed in 04d3d5f327002e13c36fdbde920ffe2347c130fe
At least I can't get them out while being sieved...

**Comment by RealGrep** [comment]
I can definitely remove a mesh while the sieve is in the middle of something. It continues to sieve until the end of the current item, and then, at least this test, it started briefly on the next but reset very quickly. I'm running with a server, perhaps there's a sync issue or something related to being on a server.

On the other hand, it doesn't seem to cause any issues. Not really a problem, but thought you'd like to know.

**Comment by MikeLydeamore** [comment]
This is probably a dumb question, but can you list the steps to do this? Do you remove the mesh with the shift-right click?

**Comment by RealGrep** [comment]
No, I just left clicked it to pick it up to the mouse cursor. Basically, just watched it sieving, and waited for the middle of the sieving progress animation, then left clicked on it. The animation continued until it finished. I assume it actually did it, but I could be wrong. I do know the animation continued all the way to the end (and a miniscule part of the next one).

**Comment by Darkosto** [comment]
The issue was when the sieving process was half finished and then you shift-rightclick.

**Comment by MikeLydeamore** [comment]
I'm going to close this, because the conversation is a bit muddled, but if there's a persisting issue, please do  open a new one.
