### ISSUE TITLE
[Bug] Crashes when using ender io conduits/pressure pipes/any fluid inserter on barrels

### ISSUE THREAD

**Issue by xelrix** [MikeLydeamore/ExNihiloAdscensio#53]
Reproduction: Attaching any ender io conduits either ON TOP or BOTTOM of a barrel. Conduits attached fine from the side.

Tested on
1.10.2-forge1.10.2-12.18.2.2179
exnihiloadscensio-1.10.2-0.1.4 and exnihiloadscensio-1.10.2-0.1.2
EnderIO-1.10.2-3.0.1.138_beta

http://pastebin.com/Bf4ik2q1

EDIT: Seems like anything that tries to connect to a barrel at the TOP or BOTTOM will crash the game. Tried with high pressure pumps from bdew's pressurized pipes mod. Crash with same log.

**Comment by jdratlif** [comment]
I'm still getting this after the patch.

http://pastebin.com/46YpxBMi

**Comment by MikeLydeamore** [comment]
Try it after 158af955a7dac97c3dd9d4d02ec3ea9b1b587bdf

**Comment by jdratlif** [comment]
That seems to have fixed it. Thanks.

**Comment by MikeLydeamore** [comment]
Great, thanks.
