### ISSUE TITLE
Default Fluid Transofrmation (witchwater) not working

### ISSUE THREAD

**Issue by Drakma** [MikeLydeamore/ExNihiloAdscensio#56]
Applying the default fluid transformation does not change water into witchwater.

`[
  {
    "inputFluid": "water",
    "outputFluid": "witchwater",
    "transformingBlocks": [
      {
        "name": "minecraft:mycelium",
        "meta": 0
      }
    ],
    "blocksToSpawn": [
      {
        "name": "minecraft:brown_mushroom",
        "meta": 0
      },
      {
        "name": "minecraft:red_mushroom",
        "meta": 0
      }
    ],
    "duration": 12000
  }
]`

Minecraft 1.10.2
Forge 2179
ENA  0.1.4

**Comment by xelrix** [comment]
Tested. The water do transform, but **very** slowly. Based on the that config (which is also a default value) and also from my playtest, it took 10 minutes!
I really doubt that was intended. A value of 1200, or 1 minute is more appropriate I think.

**Comment by Drakma** [comment]
Welp, I'm a dumb dumb.  For those that can't get it to work, the barrel goes ON TOP of the mycelium :p
