### ISSUE TITLE
heat registry for crucible

### ISSUE THREAD

**Issue by jdratlif** [MikeLydeamore/ExNihiloAdscensio#60]
I'm trying to add fire water from EnderIO as a heat source, but it doesn't seem to work.

I've seen this in the forge logs 
[15:13:43] [Server thread/DEBUG] [FML/]: The fluid EnderIO:fire_water has been selected as the default fluid for fire_water

So I'm pretty sure I have the right item name, but placing a bucket of fire water under the crucible does nothing. Is this a bug, or have I done something wrong?

http://pastebin.com/g7Cqdppj -- HeatRegistry.json

MC 1.10.2
Forge 2185
ENA 0.1.8

Thanks.

**Comment by SnakeFang** [comment]
The thing is, EnderIO:fire_water is the fluid, not the block. EnderIO happens to turn their fluids into blocks by prepending "block" and capitalizing the first letter. So in your case, use "EnderIO:blockFire_water". Also, here's a much cleaner heat registry (That I've made (hopefully) default, soon) http://pastebin.com/xT5VBWtv

**Comment by jdratlif** [comment]
Thanks. This works great.
