### ISSUE TITLE
Waila Integration for Custom Fluids is a bit off

### ISSUE THREAD

**Issue by jdratlif** [MikeLydeamore/ExNihiloAdscensio#62]
First, thanks for solving my Fire Water issues.

Second, now I see this in Waila. Solveable?

https://ibin.co/36VCa3xM6b0r.png

It calls firewater Lava, it has 7 in parenthesis, and says the rate is 0x. It is working though. The fluid under the barrel is a flowed block of fire water one away from the source block that's in the center of a 3x3 grid of crucibles, but they all say the same thing, even the one in the center.

I copied your pastebin of the soon to be new default heat registry JSON.

**Comment by SnakeFang** [comment]
Well the Liquid (Lava) means that the cobblestone is turning into lava. I don't know what's going on with the rate though, I'll see if I can recreate that.

**Comment by SnakeFang** [comment]
That's weird, I can't seem to reproduce this. You wouldn't happen to be running this on a server, would you?

**Comment by jdratlif** [comment]
Yeah, I realized about the Lava pretty soon after I posted that. And yes, I am running it on a server.

**Comment by jdratlif** [comment]
And I'm not seeing it now either. So...idk. I'll let you know if I find a way to reliably reproduce it. I feel like I updated my client side settings as the same time as the server side, but I'm using a different computer atm, so I can't be 100% sure.

Thanks for looking into it.

**Comment by SnakeFang** [comment]
Alright so I'm assuming the problem is that your configs aren't the same on the client as they are on the server. That would cause Waila to show something different from what's actually happening.
