### ISSUE TITLE
soul sand recipe not working

### ISSUE THREAD

**Issue by NarigudoBR** [MikeLydeamore/ExNihiloAdscensio#64]
when I click with sand in a wooden or stone barrel, it doesn't work, even if I use a hopper!( yes i have alredy tried adding it to the json and remaking the jsons and configs)
exnihiloadscensio 0.1.8
Ex Compressum 2.0.56

**Comment by SnakeFang** [comment]
Making soul sand is not a default recipe in this mod, if you added it you your JSON you would have to show me that I could help you.

**Comment by NarigudoBR** [comment]
please help me, because I can't do the json thing

**Comment by NarigudoBR** [comment]
here http://pastebin.com/SuJdMak0 what and where I tried

**Comment by SnakeFang** [comment]
There, it's a default recipe now, so once the update comes out you'll have to delete that config and it should generate with the soul sand recipe in there. For now http://pastebin.com/5HrPcnai should work

**Comment by NarigudoBR** [comment]
nothing to say but thank you

**Comment by MikeLydeamore** [comment]
Added in f2e596b4b382628343f1c111f708fae11e0a7425
