### ISSUE TITLE
Ender IO compatibility problems

### ISSUE THREAD

**Issue by DaNeo61** [MikeLydeamore/ExNihiloAdscensio#65]
I dont know how to describe, so here are screenshots:

Piece into Dust ?
http://puu.sh/t2zjS/e019b1b1a9.png
Dust into Dust ?
http://puu.sh/t2zc0/82831efc67.png

Chunk to Dust sounds normaly 
http://puu.sh/t2zjy/922ee6c244.png

for me it seems that this is not normaly or wished.

sorry for my grammar.

**Comment by NarigudoBR** [comment]
yeah, that's kind of a mess, and no ore doubling or way to edit it directly

**Comment by SnakeFang** [comment]
Tbh EnderIO compat is weird internally, but I fixed it in my pull request

**Comment by Ozzymud** [comment]
Can we also add a config to disable compatibility completely? I was trying to use the SAGMillRecipes_User.xml in EnderIO to add the ore doubling, and also add in bonus drops (like bonus gold from copper). But it seems that the 1:1 ratio overtook my settings. Even with this fix that doubles ores, doesn't seem like there will be a way to add in bonus drops. (My config: http://pastebin.com/fa2F7v9i)

**Comment by MikeLydeamore** [comment]
Config added in d0cb45e36573dba1cbba3c990cfc468fb6926c64
Issue fixed in 7f5bb8e9d5481b62979731e241d5a82ce83d113f
