### ISSUE TITLE
Custom Recipes Not Working

### ISSUE THREAD

**Issue by RobertLSnead** [MikeLydeamore/ExNihiloAdscensio#66]
I tried editing the .json files to add custom recipes however, it does not work and is unaffected?  Is this a known bug?

**Comment by RobertLSnead** [comment]
N/M it works, just does not show up on JEI!

**Comment by SnakeFang** [comment]
It should show up in JEI after a restart, but if you use the config reload command it will not show up. This is known and I'll take a look into it eventually, but it's not that big of a concern since it only affects the game when the config is reloaded mid-game

**Comment by Dragnier** [comment]
I've tried to add to the CrucibleRegistry for some custom recipes, but they don't work. I can't add the blocks that should melt into the crucible at all. I was trying to use Substratum liquids (redstone, glowstone, and enderpearl) as outputs for melting redstone blocks, glowstone blocks, and end stone.

**Comment by MikeLydeamore** [comment]
@Dragnier can you please provide the JSON and I'll try and test it.

**Comment by MikeLydeamore** [comment]
Please reopen if issue persists.
