### ISSUE TITLE
(question) how to edit it or compile it?

### ISSUE THREAD

**Issue by NarigudoBR** [MikeLydeamore/ExNihiloAdscensio#67]
yeah, I wanna test and maybe do some modfications

**Comment by jdratlif** [comment]
Install Minecraft Forge.
Install Java JDK 64-bit.
Download github version as zip or clone with git.
Go to command prompt in source directory and type:
gradlew setupDecompWorkspace
gradlew build
Profit. Jar file is in build/lib iirc, but I don't remember precisely.
