### ISSUE TITLE
Add support for mods to register defaults too

### ISSUE THREAD

**Issue by BrainStone** [MikeLydeamore/ExNihiloAdscensio#73]
I love to have a possibility so that other mods can add custom drops to the default config.

For example in the Class `SieveRegistry` there is a method `registerDefaults`. It gets called when no config is present. It would be very cool if I could hook into these methods so that I don't have to register my custom drops via code (which means it cannot be customized).

**Comment by MikeLydeamore** [comment]
[x] Sieve
[x] Hammer
[ ] Compost
[ ] Crook
[ ] Crucible
[ ] FluidBlock
[ ] FluidOnTop
[ ] FluidTransform
[ ] Heat
[ ] Ore*

**Comment by BrainStone** [comment]
Thank you for adding this btw!
