### ISSUE TITLE
Lag, NPE, barrels accept a stack of soul sand (or it's duped, not sure)

### ISSUE THREAD

**Issue by sitedyno** [MikeLydeamore/ExNihiloAdscensio#76]
Using Ender IO conduits with barrels leads to some non-intuitive results, an NPE, and lots of lag. The condiuts were placed on top of the barrels and configured to insert and extract without any filters. While this happened I saw traffic spike up as high as 150KB/s from the server to my client.

This gist shows the NPE and the full log is below if you need it. https://gist.github.com/sitedyno/6bc61974d7f0ae1c3befcf34e7ac760f#file-exception-log

Here is a video showing how I had set things up https://youtu.be/reEP5Z9V7fk

This is SF3 3.0.4 with:

* EnderCore-1.10.2-0.4.1.62-beta.jar        
* EnderIO-1.10.2-3.1.156.jar                
* EnderStorage-1.10.2-2.2.0.96-universal.jar
* exnihiloadscensio-1.10.2-0.1.11.jar

Thanks!

**Comment by MikeLydeamore** [comment]
So there's a few things going on here. I have been able to replicate the lag, but neither the NPE nor the dupe.
The lag is due to lighting updates, and I have a fix in mind, just need to iron out the kinks though.

**Comment by sitedyno** [comment]
Closing this since it's so old and probably not relevant at this point.
