### ISSUE TITLE
Compositing barrels somtimes "stuck" after loading world

### ISSUE THREAD

**Issue by MatthiasMann** [MikeLydeamore/ExNihiloAdscensio#78]
In single player (haven't tested it on a server) sometimes after loading the world compositing barrels are stuck. They display the dirt texture (as I'm using TOP I can't see it's internal state) but you can't remove the dirt (by right clicking with an empty hand) or add other things to it.

I don't know if I left the world while it was still composting or if it was already finished. Breaking the barrel seems to be the only fix for that.

I'm using exnihiloadscensio-1.10.2-0.1.11.jar together with ExCompressum_1.10.2-2.0.68.jar

**Comment by MatthiasMann** [comment]
This now also happened with a stone barrel connected via EIO conduits to lava producing crucibles with water on top. I have this setup so that I can make obsidian by right clicking the barrel when I need it - and I logged out with obsidian ready in the barrel - but now the barrel is stuck too.

**Comment by MikeLydeamore** [comment]
FWIW I think I fixed this in 5c4ce92384b72761d3d6494310048d5498c8c69e

Please re-open if it persists.
