### ISSUE TITLE
Document OreRegistry in wiki

### ISSUE THREAD

**Issue by Flabort** [MikeLydeamore/ExNihiloAdscensio#82]
I am building a pack with mods that are not by default supported by your mod's autocomplete feature. A lot of these mods add new ores which do not get added to the OreRegistry JSON, and without any clue how I'm supposed to add these ores manually, I tried to add one ore as a test. I didn't change anything else in the file, but adding the ore caused none of them to generate chunks or pueces when I loaded up the game. 

for reference, what I tried to add was Adamantine from Base Metals; I would have added the rest if the test had worked.

`{
  "name": " adamantine",
  "color": {
    "r": 0.2,
    "g": 0.2,
    "b": 0.2,
    "a": 1.0
  },
 "result": {
    "name": "basemetals:adamantine_ingot",
    "meta": 0
  }
}`

So knowing what all possible variables are in the wiki would help.

**Comment by MikeLydeamore** [comment]
I took your provided example to test, and it seemed to work just fine (except for a leading space after name). Can you provide the full JSON? It may just be a missing comma. 

I have also added some documentation: https://github.com/MikeLydeamore/ExNihiloAdscensio/wiki/OreRegistry

**Comment by Flabort** [comment]
Well, I deleted the file without backing it up to get it to regenerate the defaults, but here's what I think I had.
http://pastebin.com/pSvJzMiw
This is me trying to add a single ore out of the... *nervous chuckle*... 31 ore added by the mods in my pack which aren't automatically generated.
.... and for whatever reason, this time it worked. Way to go, passive IT field. 

It was probably the leading space. :) Thank you. Now for 30 more entries :P
