### ISSUE TITLE
Breaking (at least) heavy sieves with the mesh still inside deletes the mesh

### ISSUE THREAD

**Issue by herrgutt** [MikeLydeamore/ExNihiloAdscensio#83]
As title says.
Tried in recommended version of FTB Sky Factory 3.
Chopped 25 heavy sieves with an axe **using the veinmining** feature. All the iron stiffened meshes was deleted.
I am not sure if this is a problem with the veinminer mod, or your mod.

Thanks in advance.

**Comment by MikeLydeamore** [comment]
Heavy Sieves are added by Ex Compressum, not Ex Nihilo, so I have no power over their behaviour.

I just checked this with the sieves added by Ex Nihilo, and they dropped meshes successfully. Please reopen if the issue persists for you using a regular sieve.
