### ISSUE TITLE
Unable to change composting

### ISSUE THREAD

**Issue by NemmieDragon** [MikeLydeamore/ExNihiloAdscensio#86]
In the config file when i change 
composting {
    I:ticksToFormDirt=600
}

I have tried from 1 to 1000 no different

**Comment by NemmieDragon** [comment]
I want to change how fast the composting take am I over looking anything?

**Comment by MikeLydeamore** [comment]
The config is working fine for me. Did you save the config, and then restart minecraft?

**Comment by NemmieDragon** [comment]
Yes I stopped the server, changed from 600 to 20 just to check. saved and restarted the server. still took the same amount of time to compost. went back into the config and it says 20 so I changed it to 1000 saved  started the server and same thing still staying the normal rate.

**Comment by MikeLydeamore** [comment]
Did you change both the client and the server?

**Comment by MikeLydeamore** [comment]
Not quite sure what could be causing this, it is working fine in all of my tests.
