### ISSUE TITLE
Updated some mods (can't remember which), sieving stops working, console reports malformed JSON

### ISSUE THREAD

**Issue by Flabort** [MikeLydeamore/ExNihiloAdscensio#87]
Pastebin link for sieve JSON file:
http://pastebin.com/kHM0mv58

So I had a working sieve JSON file, at least it was working afaik, but I updated a few mods at once, as far as I know this includes Chance Cubes (already confirmed to not be them), I think Code Chicken core and Code Chicken Lib, Advanced Generators, and 2 or 3 others that I can't remember. 

The source of my belief that one of the mods I updated being the cause (quite possibly Code Chicken Lib?) comes from several malformed JSON reports in the console. Here's two of them:

`[01:56:28] [Client thread/INFO] [STDERR]: [codechicken.lib.model.blockstate.CCBlockStateLoader:load:126]: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected name at line 8 column 6`

`[01:56:28] [Client thread/INFO] [STDERR]: [codechicken.lib.model.blockstate.CCBlockStateLoader:load:126]: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected name at line 8 column 6
`

I can't figure out what broke it, if I wrote some of my JSON wrong, or if another mod which I updated broke JSON reading. As far as I can tell, the only Ex Nihilo JSON file affected is Sieve Registry, the other JSONs load fine. This makes me suspect that I did something wrong, that it wasn't a mod. But I can't remember changing the JSON recently.

So 50% chance I broke it, and can't see where I broke it, and 50% chance another mod broke it.

So I don't have to share custom scripts and my other JSON edits for compatibility with all the individual mods in my pack-in-development individually, I have created a Curse Profile which you can import:
https://drive.google.com/file/d/0B0dRWbDnsi70WEJ0dTBWVlZ5WFk/view?usp=sharing

**Comment by MikeLydeamore** [comment]
What you are seeing is Malformed JSONs due to model loading. Models are the shapes for all blocks in Minecraft. It is unrelated to the sieve JSON.

I am not sure why your sieves are not working. I had a quick look at the JSON and it seemed OK. If you have removed or updated a mod that has changed what ores are available, that may cause side effects?

**Comment by Flabort** [comment]
Well, thank you even if the issue is not something you can fix on your end; You at least are helping me narrow down the problems. I should point out that the ore registry JSON file is still working, and your mod is still generating pieces, chunks, and dusts for all the ores. I'll look at the stuff that's supposed to be produced by the sieve that isn't an ore piece.

**Comment by Flabort** [comment]
I did find some misspelled stuff in the JSON.

1) Misspelled Avocado (Avacado) in harvestcraft:avocado_sapling
2) Misspelled Cinnamon (Cinamon) in harvestcraft:cinnamon_sapling

Fixed these but the sieve still doesn't work.

**Comment by Flabort** [comment]
Thanks to http://www.jsoneditoronline.org/ I was able to find where I had an extra comma and had one missing, and with those two commas fixed it all works now. Definitely a tool I will recommend people use when trying to solve JSON issues.
