### ISSUE TITLE
Ability to register wildcard entries into registries

### ISSUE THREAD

**Issue by blay09** [MikeLydeamore/ExNihiloAdscensio#88]
I'm adding wood chippings for all vanilla log variants. Been using `HammerRegistry.register` and just updated to the new `DefaultRecipeHandler` thing to make it work on the latest version, and (unsurprisingly) ended up with a [huge HammerRegistry](http://pastebin.com/X9Rz7V77). They're all the same though and it seems that the json format supports wildcards using `*`, it's just that I can't register wildcard stuff without cheating by manipulating the registry directly (which I'd rather not do since that just makes further breaking more likely).

Would be nice to have a `boolean wildcard` parameter in the register method or something similar.

**Comment by SnakeFang** [comment]
Could you try using a -1 for the meta?

**Comment by blay09** [comment]
The [method](https://github.com/MikeLydeamore/ExNihiloAdscensio/blob/e0e890d7ebfee2c8f135abdee352068f27804b8b/src/main/java/exnihiloadscensio/registries/HammerRegistry.java#L106-L119) expects an `IBlockState` and serializes it into meta itself in `HammerRegistry.register`, I can't pass it as an int.

Also [here's](https://github.com/blay09/ExCompressum/blob/1.10.2/src/main/java/net/blay09/mods/excompressum/compat/exnihiloadscensio/ExNihiloAdscensioAddon.java#L64-L81) my current code for reference.

All that aside there's another issue with the current system in that if an addon is added later on and the configs were already generated, new defaults that would normally be there won't be there. I think what I _actually_ need is an event that's fired after Adscensio has loaded its json registries, and then I can still control insertion of my additional entries via my own config options. That could probably go into its own issue, I'll write one up later.

**Comment by SnakeFang** [comment]
Tbh if it was my mod I'd do all the registry stuff way differently.

**Comment by SnakeFang** [comment]
I could rework the whole system but then Insane (author) seems to already be working on it, and I don't know if he'd appreciate all he's doing being replaced

**Comment by SnakeFang** [comment]
Alright time for a rewrite of the registry/configuration system :D (kill me)

**Comment by MikeLydeamore** [comment]
It will have to not break existing json files though.

**Comment by SnakeFang** [comment]
It will convert existing configs to the new system

**Comment by SnakeFang** [comment]
It'll take a few days (mostly cause I have exams for the next 3 days), so for now I guess players can deal with huge json files
