### ISSUE TITLE
API Request: RegistryReloadEvent

### ISSUE THREAD

**Issue by blay09** [MikeLydeamore/ExNihiloAdscensio#92]
I need to register wood chippings via code as the defaults system is not a viable solution yet (only works if both mods were present the very first time it was run - e.g. all packs had to update their configs manually now to get the change in).

Once #91 is fixed I'll be able to do that normally in `init` like I did before, but that will only last until configs are reloaded via your config reload command. The simplest solution to this would be firing an event on the `MinecraftForge.EVENT_BUS` after you've loaded your JSON registry. I can subscribe to that and do my runtime-changes right after.

**Comment by MikeLydeamore** [comment]
I've never done those before, so not sure what fields you'd like to access, but do let me know.

**Comment by blay09** [comment]
That should already be enough by itself. I'll be implementing the fix on my side once it's up on Curse. Thanks!

**Comment by MikeLydeamore** [comment]
Great, thanks.
