### ISSUE TITLE
Sieve crafting recipies not showing up (adscensio)

### ISSUE THREAD

**Issue by Flyer173** [MikeLydeamore/ExNihiloAdscensio#95]
Whenever i try crafting a sieve **with a mesh** it wont pop up. i use not enough items so that is how i know this problem. Anybody have solutions??? If more info is needed, i am happy to help

**Comment by Flabort** [comment]
Don't craft it with the mesh. Place the sieve, craft the mesh seperately, and right click the empty sieve with the mesh in your hand.
